import type { Metadata, Viewport } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Cyril's Portfolio",
  keywords: [
    "Cyril Imperial",
    "Portfolio",
    "Web Developer",
    "Software Engineer",
    "Next.js",
    "React",
    "JavaScript",
    "TypeScript",
    "CSS", 
    "HTML",
    "Web Design",
    "UI/UX",
    "Full Stack Developer",
    "Frontend Developer",],
  authors: [{ name: "Cyril Imperial" }],
  creator: "Cyril Imperial",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
